title: MCC.py Órai Anyag
description: Ez az oldal a MCC.py órai anyagának részletes leírását és gyakorlati feladatait tartalmazza. Az anyag célja, hogy bemutassa a Python programozás alapjait kezdők számára. Az oktatási anyag tartalmaz példákat, feladatokat és magyarázatokat a Python nyelv alapvető fogalmairól.
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

social:
  twitter: "your_twitter_handle"
  github: "your_github_handle"
  linkedin: "your_linkedin_handle"
language: "hu"
